### ISSUE TITLE
FAQ page content

### ISSUE THREAD

**Issue by nstringham** [kendoclub-at-umich/website#11]
determine if this is necessary and then implement it if it is

**Comment by nstringham** [comment]
We think that [Pico Accordions](https://picocss.com/docs/accordion) are a good fit for this page.

**Comment by nstringham** [comment]
@Archie-G will write the content for this and then someone can convert it you svelte/pico code

**Comment by Archie-G** [comment]
[KendoClubWebsiteFAQ_AG20240616.docx](https://github.com/user-attachments/files/15861221/KendoClubWebsiteFAQ_AG20240616.docx)
[KendoClubWebsiteFAQ_AG20240616.pdf](https://github.com/user-attachments/files/15861222/KendoClubWebsiteFAQ_AG20240616.pdf)

I did my best to shorten everything. See what you all think. Also please correct any English mistakes/typos I made lol.
