### ISSUE TITLE
Add description to each page

### ISSUE THREAD

**Issue by nstringham** [kendoclub-at-umich/website#115]
https://developer.chrome.com/docs/lighthouse/seo/meta-description

**Comment by nstringham** [comment]
related to #147

**Comment by zalhabash** [comment]
Meta descriptions for remaining pages not converted from pdfs yet, for a future PR:

- Kendo Japanese Pronunciation and Definitions: "Basic Japanese language pronunciation guide and large kendo vocabulary  list. Includes context about phonetics and characters."
- Parts of a Shinai and How To Hold It: "Labelled shinai diagrams, and how to hold a shinai, with pictures from multiple angles."
