### ISSUE TITLE
Resources page content (see comment)

### ISSUE THREAD

**Issue by nstringham** [kendoclub-at-umich/website#13]
Go through resources content on the old website. Remove outdated links, and add the rest onto the resources page.

**Comment by zalhabash** [comment]
Pages to consider transferring info from:

- Current resources pages
- [What is Rei?](https://websites.umich.edu/~kendoclub/whatisrei.html) (keep some of this on home page, about what is kendo?)
- [What is Kendo?](https://websites.umich.edu/~kendoclub/whatiskendo.html)

Should we rename this page to something more descriptive? "Education", "Additional Info"...?
