### ISSUE TITLE
Create timeline for publishing (sprints)

### ISSUE THREAD

**Issue by zalhabash** [kendoclub-at-umich/website#19]
Current draft:

## Time estimates

**Previous features**

- Build/other tools setup: 4-5 hrs
- Website theme: 6-10 hrs
- Calendar page initial setup: 5-7 hrs

**Features to publish**
(In order of what should get done first to show bare minimum to stakeholders as soon as possible. Features closest to the end the ones I would be least disappointed about never getting done.)

3 week sprints (24 hrs)

### Sprint 1

- Write home page content (writing): 2 hrs
- Write contact us page content: 1.25 hrs
- Write about us page content: 3 hrs
- Make navigation bar: 6 hrs
- Style pages: 8 hrs

- Get stakeholder feedback: 4 hr

24.25 hrs

### Sprint 2

- Content/styling iterations: 8 hrs
- Write FAQ page content: 3 hrs
- Write Resources page: 4 hrs
- Start adding hoverability to calendar events: 4 hrs

- Get stakeholder feedback: 4 hr

23 hrs

### Sprint 3

- Content/styling iterations: 8 hrs
- Add hoverability to calendar events: 4 hrs
- Publish website: 8 hrs

- Get stakeholder feedback: 4 hr

24 hrs

### Sprint 4: Production Support

- Collect feedback from users

## Features to complete before publishing:

- Home page, Contact Us, About us, FAQ page, Resources pages 
  - Content (writing task)
  - Style
- Navigation bar
- Calendar with up-to-date events I should have
  - (maybe) hoverable events with details

## Features not to complete before publishing:

- Gallery

**Comment by nstringham** [comment]
@zalhabash don't forget to close the issue if this is done.
