### ISSUE TITLE
Make website installable

### ISSUE THREAD

**Issue by nstringham** [kendoclub-at-umich/website#205]

**Comment by nstringham** [comment]
After looking into some available solutions I think this is probably more work than it's worth. We have excellent caching and most mobile browser can recover tabs without Internet. A service worker would require clients to download many versions of the same image including ones they will never display. I think supporting printing should be sufficient to make Joe Sensai happy so this is probably not necessary. What do you think @zalhabash

**Comment by zalhabash** [comment]
Sounds good to me. I agree that supporting printing is a good solution.
